# Generated by Django 4.1.5 on 2023-02-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='olchov',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
